services:
  - type: web
    name: dragify-task-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_BASE_URL
        value: https://ai-integration-1ojr.vercel.app
    autoDeploy: false
